@API_KEY = 1234

POST http://localhost:8787/css
Authorization: Bearer {{API_KEY}}
Content-Type: application/json

{
  "html": "<div class='bg-blue-500 text-white p-4 rounded-lg shadow-md'>
          <h1 class='text-2xl font-bold mb-2'>Hello Tailwind!</h1>
          <p class='text-gray-100'>This is a test with Tailwind CSS JIT.</p>
          <button class='bg-red-500 hover:bg-red-600 px-4 py-2 rounded mt-4'>
            Click me
          </button>
        </div>",
  "css": "h1 { color: red; } .unused { display: none; } p { font-size: 16px; }"
}

######
GET http://localhost:8787/
Authorization: Bearer {{API_KEY}}